projects:
    ff:
        id_type: semver
        dashboards:
          - name: 'overview'
            charts:
            - name: 'request durations'
              unit: ms
              metrics:
                - add.avg
                - delete.avg
                - update.avg
            - name: 'code coverage'
              metrics:
                - loc.total
                - loc.covered
